
platform :ios, '9.0'
use_frameworks!

target 'LoveNews' do
 pod 'Alamofire', '~> 4.7.0'
 pod 'SnapKit', '~> 4.0.0'
 pod 'AlamofireObjectMapper', '~> 5.0.0'
 pod 'AlamofireImage', '~> 3.3.0'
 pod 'MBProgressHUD', '~> 1.1.0'
 pod 'VGPlayer', '~> 0.2.0'
end


